    project: VONE-DRL
    name: "Agent Routing Separate"
    program: main.py
    method: bayes
    metric:
      name: mean_reward
      goal: maximize
    parameters:
      learning_rate:
        min: 0.0003
        max: 0.0015
      gamma:
        min: 0.5
        max: 0.7
      n_steps:
        min: 40
        max: 80
    command:
      - ${env}
      - ${interpreter}
      - ${program}
      - "--file"
      - "./config/config_routing_separate.yaml"
      - "--log"
      - "WARN"
      - "--masking"
      - ${args}
    early_terminate:
      eta: 3
      max_iter: 27
      s: 2
      type: hyperband