    project: VONE-DRL
    name: "Agent CONUS"
    program: train.py
    method: bayes
    metric:
      name: mean_reward
      goal: maximize
    parameters:
      gamma:
        min: 0.8
        max: 0.98
      n_steps:
        values:
          - 50
          - 100
          - 150
          - 200
          - 250
          - 300
      gae_lambda:
        min: 0.9
        max: 0.99
      batch_size:
        values:
          - 25
          - 50
          - 100
      use_afterstate:
        values:
          - True
          - False
      num_layers:
        values:
            - 2
            - 3
      num_hidden:
        values:
            - 64
            - 128
            - 256
    command:
      - ${env}
      - python3
      - ${program}
      - "--env_file"
      - "./config/agent_conus.yaml"
      - "--log"
      - "WARN"
      - "--total_timesteps"
      - 5000000
      - "--masking"
      - "--multistep_masking"
      - "--multistep_masking_n_steps"
      - 5
      - "--save_model"
      - "--reward_success"
      - 0
      - '--reward_failure'
      - -10
      - "--lr_schedule"
      - "linear"
      - ${args}
    early_terminate:
      eta: 2
      min_iter: 24
      s: 4
      type: hyperband
