    project: VONE-DRL
    name: "Agent Unsorted Combined Masked"
    program: main.py
    method: bayes
    metric:
      name: mean_reward
      goal: maximize
    parameters:
      learning_rate:
        min: 0.0003
        max: 0.002
      gamma:
        min: 0.5
        max: 0.7
      n_steps:
        min: 40
        max: 80
      linear_scheduler:
        values:
          - 0
          - 1
    command:
      - ${env}
      - ${interpreter}
      - ${program}
      - "--file"
      - "./config/config_agent_masked.yaml"
      - "--log"
      - "WARN"
      - "--masking"
      - "--recurrent_masking"
      - "--linear_scheduler=1"
      - "--save_model"
      - ${args}
    early_terminate:
      eta: 3
      max_iter: 27
      s: 2
      type: hyperband