project: VONE-DRL
env_name: vone_Env-v0
env_args:
    episode_length: 10000
    load: 180
    mean_service_holding_time: 10
    k_paths: 5
    topology_name: nsfnet
    num_slots: 320
    node_capacity: 50
    min_node_cap_request: 1
    max_node_cap_request: 2
    min_slot_request: 2
    max_slot_request: 4
    min_vnet_size: 3
    max_vnet_size: 3
    vnet_size_dist: fixed