project: VONE-DRL
env_name: vone_Env_MultiDim-v0
env_args:
    episode_length: 50000
    load: 1000
    mean_service_holding_time: 10
    k_paths: 5
    topology_name: acmn
    num_slots: 100
    node_capacity: 50
    min_node_cap_request: 1
    max_node_cap_request: 2
    min_slot_request: 2
    max_slot_request: 6
    min_vnet_size: 3
    max_vnet_size: 3
    vnet_size_dist: fixed
    num_nodes: 100
    connectivity: 0.8