project: VONE-DRL
env_name: vone_Env_MultiDim-v0
env_args:
    episode_length: 10000
    load: 100
    mean_service_holding_time: 10
    k_paths: 5
    topology_name: conus
    topology_path: ./topologies/CORONET_CONUS_Topology.json
    num_slots: 320
    node_capacity: 30
    min_node_cap_request: 1
    max_node_cap_request: 2
    min_slot_request: 2
    max_slot_request: 8
    min_vnet_size: 3
    max_vnet_size: 3
    vnet_size_dist: fixed